import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [listText, setListText] = useState("");
  const list = listText ? listText.split(",") : [];

  const randomRandomizedList = list.sort(() => Math.random() - 0.5);

  return (
    <div className={styles.container}>
      <Head>
        <title>Stand up Order!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Standup Order!</h1>
        <textarea
          style={{
            width: 400,
            height: "100px",
            fontSize: 14,
            padding: 10,
            marginTop: 30,
          }}
          onChange={(e) => setListText(e.target.value)}
          value={listText}
          placeholder="Enter names separated by commas"
        />
        <ol style={{ marginLeft: -40 }}>
          {randomRandomizedList.map((item, index) => (
            <li
              key={index}
              style={{
                width: 400,
                padding: 10,
                background: "#444",
                marginTop: 10,
              }}
            >
              {item}
            </li>
          ))}
        </ol>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
